### PR TITLE
Fix control codes being used for mod list sort. Clean up sorting code.

### PR DESCRIPTION
**Pull request by tterrag1098**
If a mod used a control code at the beginning of its name, it was always sorted at the bottom (MrCrayfish does this with his mods). I took this chance to get rid of the anon classes as well, in favor of a much cleaner interpretation.

This test mod works perfectly fine:
```
@Mod(name = "\u00a7aDebugName", modid = "ForgeDebugModName", version = "1.0")
public class ModNameDebug {}
```

### CODE REVIEW

**Comment by tterrag1098** [comment]
Oops, also just found a small bug with the right-click handling. Fixed that as well.

**Comment by LexManos** [comment]
But if you get rid of the color codes then you're not sorting by mod name.
If the modder wants to be stupid and include non-ascii in their name then thats on them. 
The other part of this, the code cleanup, not really needed.

**Comment by tterrag1098** [comment]
@LexManos Um...what? Why should color codes be included in sorting? They are non-alphanumeric. Also this PR includes a few bugfixes.

**Comment by LexManos** [comment]
It NOW contains bug fixes because you pushed those in in an attempt to justify the rest of the PR.
The question is, why SHOULDN'T it be in sorting? 
It's part of the mod name, just because it isn't alphanumeric doesn't mean it isn't part of the mod name.
Point is, Whoever the hell is writing a mod with non-alphanumeric names is stupid and should stop.

**Comment by tterrag1098** [comment]
Nice assumption, but really I just noticed a bugfix and pushed it to save PRs. I'm fine to go back and make another PR with just the bugfix.

**Comment by cpw** [comment]
The only comment I'll make @LexManos is that colour codes are invisible parts to a name. Probably, what needs to happen is that there is a separate "decorated name" that allows for a decorative name presentation including colour codes...

**Comment by LexManos** [comment]
Thats what I was thinking, but i'm also thinking of forcing mods in 1.8.3 to ONLY have the normal [a-zA-Z0-9._\-]+
If we want to add a separate 'fancy' display version fine, but I just see people being stupid and making rainbow names. Aside from vanity what reason would there be to allow color codes in display names? It also removes our possibility to use color codes for functional things {Enabled status, sub-mod display, or what have you}
Is there a good reason to allow it? Either we strip it all or we allow it all.

**Comment by cpw** [comment]
Lex, I was commenting on the stripping.. The list should only display a stripped name, for certain. Colour in the list is for status and other information. The name displayed on the main info panel could be rainbow for all I care.. It conveys no info there..

**Comment by LexManos** [comment]
Whatever I dont care enough about this to argue anymore..

**Comment by tterrag1098** [comment]
@cpw This PR doesn't change what displays, the list will still show colored names. It only strips it for sorting.

**Comment by LexManos** [comment]
There, done properly: https://github.com/MinecraftForge/FML/commit/471f1451c383369e9630acb170eb4f4d98d81c3d

**Comment by tterrag1098** [comment]
@LexManos Fair enough, that looks good.

**Pull request merged**
