### PR TITLE
updated to latest stable mappings (stable_16)

### PR DESCRIPTION
**Pull request by bspkrs**

### CODE REVIEW

**Comment by bspkrs** [comment]
Also: https://github.com/MinecraftForge/MinecraftForge/pull/1706

**Comment by LexManos** [comment]
1) I prefer using the base numbered one so we have a date reference.
2) Why? The current set is just fine to work with.

**Comment by bspkrs** [comment]
1. I could change it to the snapshot from that day and probably be fine.
2. There were a number of 1.8 name changes that were undone due to them being unnecessary changes to existing names, so I thought it best to force people to use more up-to-date mappings sooner rather than later.

It doesn't matter to me, just trying to help.

**Comment by LexManos** [comment]
This doesn't force people to do anything. It just changes what we use in dev, and the default put in the shipped src zip. Either way, meh.

**Comment by bspkrs** [comment]
Okie, whatevs! :P

**Pull request closed without merging**
