### PR TITLE
Updated to Gradle 2.2.1

### PR DESCRIPTION
**Pull request by Parker8283**
Tested extensively, and nothing is broken. All works.

### CODE REVIEW

**Comment by ntzrmtthihu777** [comment]
You know... Mayhaps we should remove the first line from the gradle-wrapper.properties file so we have less extraneous file changes.

**Comment by Parker8283** [comment]
What does it matter? You still have to change the file

**Comment by AbrarSyed** [comment]
pretty sure the version tells it what to download. IIRC the jar thats there is only to downlaod the specified version and launch it.

**Comment by ntzrmtthihu777** [comment]
Just a thought. Just something I personally do because I prefer succinct diffs and so forth.

**Comment by Parker8283** [comment]
Anyways, would like this merged, as people are still using Gradle 2.0, and it would probably be a good idea to start shipping this version with the new src distros.

**Pull request closed without merging**
