### PR TITLE
Splash screen implementation

### PR DESCRIPTION
**Pull request by RainWarrior**
Motivation: MinecraftForge/MinecraftForge#1764
Demonstration: http://www.youtube.com/watch?v=yqVw3Z_u_D4
Test code used in the video: https://gist.github.com/RainWarrior/b42b24f0cf5e328078e5

### CODE REVIEW

**Comment by heldplayer** [comment]
Is what this displays exactly like what the video demonstrates? If so, it looks horrible in my opinion (sorry)

Maybe keep the Mojang logo visible and instead of covering it, put the progress bars at the bottom and get rid of the spinning triangle?

**Comment by RainWarrior** [comment]
First I'll make it work, then I'll make it pretty. Also, logo is back, and colors are a bit tweaked compared to the video.

**Comment by CreativeMD** [comment]
Nice job :D i think you are more prepared to do this. Hope i can see this being implemented soon.

**Comment by Kubuxu** [comment]
Which level of GL is required for SharedDrawable to work?

**Comment by laci200270** [comment]
This is very good idea! I want this in forge :)

**Comment by RainWarrior** [comment]
Be patient, it's being tested in 1.7, and will probably eventually be in 1.8, from the looks of things :P

**Comment by cpw** [comment]
It'll be there very soon. I think the main blocker is the weird texture issue a few people on macbooks have seen.

**Comment by LexManos** [comment]
This has been merged into 1.7 and 1.8, so closing.

**Pull request closed without merging**
