### PR TITLE
Update to ASM5 for Java 8 support

### PR DESCRIPTION
**Pull request by Grinch**
SpecialSource updated ASM5 and ForgeGradle supports ASM5 as well but neither FML or Forge were actually updated to support ASM5 opcodes. This commit resolves this.

Signed-off-by: Steven Downer <grinch@outlook.com>

### CODE REVIEW

**Comment by diesieben07** [comment]
#550 :(

**Comment by immibis** [comment]
Because using Java 1.8 is stupid, apparently.

**Comment by asiekierka** [comment]
Minecraft doesn't target it. Except the new launcher does. Except it's not out yet.

**Comment by diesieben07** [comment]
It is out. And Mojang is starting to [push people](https://twitter.com/SeargeDP/status/561178272323891201).

**Comment by TechStack** [comment]
Also this on java 8 today from Dinnerbone: https://twitter.com/Dinnerbone/status/561096484981334016.

**Comment by LexManos** [comment]
My reasoning still stands, it would require them a new Minecraft version to FORCE java 8 requirement. As such I do not want to ACTIVELY ENCOURAGE modders to preemptively REQUIRE java 8 by doing this.
Once java 8 is required by Vanilla itself I fully intend on pulling this. (Or something similar).

Unless someone wants to go through and write an additional transformer here that prevents loading of mods that use java8 bytecode and throws a giant warning saying that they are using java 8 to early. Which I can remove in MC 1.9/1.10 when java 8 is the standard.

**Comment by Kubuxu** [comment]
Should we allow modders to use Java 8? Yes??

**Comment by LexManos** [comment]
No.

**Comment by Furyhunter** [comment]
You can use Java 8 lambdas in Java 7 using [RetroLambda](https://github.com/orfjackal/retrolambda), if that suits your fancy. You won't have access to JDK8 API, obviously.

**Comment by immibis** [comment]
I'm guessing the difference between allowing mods to require Java 8, and allowing mods to require Scala, is that the Scala libraries are redistributable and can be automatically downloaded.

**Comment by matthewprenger** [comment]
I agree with everyone else. Modders should have the ability to target Java 8 if they wish to.

**Comment by asiekierka** [comment]
I disagree. Lex has a point here.

However, this makes modders who are making mods with a long-term plan somewhat limited. But we're an edge case, and we have solved that edge case for private development.

**Comment by LexManos** [comment]
You know what i'm sick of it. New rule anyone who asks for java 8 help is instantly banned from EVERY FUCKING THING related to Forge.
Asiekaerka you're bullshit 'lets transform Forge because I want to be a special little snowflake and screw people over' is getting really god damn annoying.

**Comment by asiekierka** [comment]
@LexManos - No. It's for private development.

NOVA is slated for release in Summer 2015. We want to develop it SOMEHOW until then.

**Comment by LexManos** [comment]
Private development my ass, public repo advocating fucking around in Forge internals IS NOT PRIVATE.
Seriously if there was a feasible way to prevent you guys from having that ability then I would do it, sadly Its not worth the fucking futile effort and cat/mouse game to try and prevent you guys from doing it. Only recourse I have is to show how fuckling pissed off I am when you fuck heads do it.

**Comment by asiekierka** [comment]
@LexManos - It's only public because I can't shell out the money for a big enough GitHub private repo, and I like GitHub.

I planned to remove it for the far off public release, this was only so we could actually test the Java 8-dependent API before release. We did not want to release it publicly with this hack in, this was PURELY for development reasons.

**Comment by RCIX** [comment]
So wait, you're banning asie off of Forge because he's doing (functionally) private development on another project for shim compatibility to resolve a temporary situation? Way to burn bridges. *gets popcorn*

**Comment by LexManos** [comment]
No actually it wouldn't There are plenty of ways to emulate the systems you want from java 8 without forcing java 8. So you could easily develop whatever the hell you want targeting java 6/7.
But no you guys have to fucking take it upon yourself to hack into FML because you feel like being special instead of putting forward the effort to work within the constraints of the current Minecraft platform.

I still can't understand how people find it so hard, LESS than 1/2 of the users of Minecraft use java 8, Forcing java 8 means you alienate OVER 1/2 of the users... seriously how is this a good idea?

I would LOVE to re-write a lot of the shit in Forge to take advantage of some of the Java 8 features such as default implementations but I can't Because Minecraft doesn't target 8. Its a simple concept, how am I the only one who see it...

**Pull request merged**
