### PR TITLE
Improve mod list GUI, adds sort buttons and a search bar

### PR DESCRIPTION
**Pull request by tterrag1098**
This makes the mod list GUI much easier to use, as you can sort alphabetically (or reverse alphabetically) and search by name.

Here's a screenshot of what the new GUI looks like, there are minimal changes to the existing layout other than some minor shifting of the buttons to fit in the search bar:

### CODE REVIEW

**Comment by tterrag1098** [comment]
And yes the screenshot is from 1.7, I made it with a hacky mod there first, but I promise it looks the same :P

It's just not as interesting with so few mods

**Comment by gigabit101** [comment]
Looks awesome

**Comment by tterrag1098** [comment]
Fixed the indent on the `continue;`

**Comment by coolsquid** [comment]
Looks awesome! Also, could you release the 1.7.10 version you made?

**Comment by matthewprenger** [comment]
:+1:

**Comment by tterrag1098** [comment]
@coolsquid It's part of [ttCore](http://minecraft.curseforge.com/mc-mods/226082-ttcore/files) (only the alphas so far).

**Pull request merged**
